server:
  port: 8080

eureka:
  client:
    register-with-eureka: false # 默认为true。false表示不向注册中心注册自己
    fetch-registry: true # 默认为true。false表明自己就是注册中心，职责就是维护服务实例，不需要检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka/