server:
  port: 8000
  servlet:
    context-path: /springboot
spring:
  application:
    name: shiro_springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql//localhost:3306/003_shiro_springboot?serverTimezone=Asia/Shanghai
    username: root
    password: wj113