server:
  port: 9527

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: payment_routh # 路由ID,没有规定的规则,但要求唯一
          uri: http://localhost:8001
          predicates:
            - Path=/payment/list/** # 断言，路径相匹配的进行路由

        - id: payment_routh # 路由ID,没有规定的规则,但要求唯一
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由