server:
  port: 9527

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh # 路由ID,没有规定的规则,但要求唯一
#          uri: http://localhost:8001
          uri: lb://cloud-provider-payment # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/list/** # 断言，路径相匹配的进行路由

        - id: payment_routh # 路由ID,没有规定的规则,但要求唯一
#          uri: http://localhost:8001
          uri: lb://cloud-provider-payment # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由