server:
  port: 8001

spring:
  application:
    name: nacos-payment
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # 配置Nacos地址

# 消费者将要去访问的微服务名称（注册成功进Nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-provider
