server:
  port: 8000
  servlet:
    context-path: /springboot
spring:
  application:
    name: 008_mp_springboot
  profiles:
    active: local

#配置mybatis plus
mybatis-plus:
  type-aliases-package: com.clw.domain.*
  mapper-locations: mapper/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
