server:
  port: 8003

spring:
  application:
    name: cloud-provider-payment-hystrix

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/

