# Base Config
server:
  port: 8002

spring:
  application:
    name: cloud-provider-payment

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cloud.upenv.com:7707/sp01?serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  type-aliases-package: com.clw.entity
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: assign_uuid

eureka:
  client:
    register-with-eureka: true # 默认为true。false表示不向注册中心注册自己
    fetch-registry: true # 默认为true。false表明自己就是注册中心，职责就是维护服务实例，不需要检索服务
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/
  instance:
    instance-id: payment8002 # 主机名称
    prefer-ip-address: true # 开启Ip显示